[tool.poetry]
name = "snake-game"
version = "0.1.0"
description = ""
authors = ["myashchenko"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
